### ISSUE TITLE
new version for latest changes

### ISSUE THREAD

**Issue by stojg** [echoes-tech/puppet-monit#14]
Is it possible to release a new version of this module on puppet forge? I'm very keen on using the https://github.com/echoes-tech/puppet-monit/commit/c0d96870a871dfeba593036b6ccd2d29a8373e41 on our production systems.

and Thanks for a solid module!

**Comment by floSoX** [comment]
Hi,

Thanks for your interest.
I will publish a new release today.

Regards,

**Comment by stojg** [comment]
Thanks!
